# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Xuelin Li
description: >- # this means to ignore newlines until "baseurl:"
  Assistant Professor of Finance, Columbia Business School.
baseurl: "/homepage" # the subpath of the site
url: "https://lixx3811.github.io" # the base hostname & protocol for the site
og_image: /assets/img/photo.jpg
google_analytics: "UA-147588751-1"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Discussion&Teach

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: xuelin.li@columbia.edu
      link: mailto:xuelin.li@columbia.edu
  follow:

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
